/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcRibbonTable {
    'baseApiUrl': string;
    'data': string;
    'groupBaseUrl': string;
    'subjectBaseUrl': string;
  }
}

declare global {


  interface HTMLWcRibbonTableElement extends Components.WcRibbonTable, HTMLStencilElement {}
  var HTMLWcRibbonTableElement: {
    prototype: HTMLWcRibbonTableElement;
    new (): HTMLWcRibbonTableElement;
  };
  interface HTMLElementTagNameMap {
    'wc-ribbon-table': HTMLWcRibbonTableElement;
  }
}

declare namespace LocalJSX {
  interface WcRibbonTable {
    'baseApiUrl'?: string;
    'data'?: string;
    'groupBaseUrl'?: string;
    'subjectBaseUrl'?: string;
  }

  interface IntrinsicElements {
    'wc-ribbon-table': WcRibbonTable;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wc-ribbon-table': LocalJSX.WcRibbonTable & JSXBase.HTMLAttributes<HTMLWcRibbonTableElement>;
    }
  }
}


