/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcLightModal {
        "close": () => Promise<void>;
        "modalAnchor": string;
        "modalContent": string;
        "modalTitle": string;
        "open": () => Promise<void>;
        "toggle": () => Promise<void>;
        "x": number;
        "y": number;
    }
}
declare global {
    interface HTMLWcLightModalElement extends Components.WcLightModal, HTMLStencilElement {
    }
    var HTMLWcLightModalElement: {
        prototype: HTMLWcLightModalElement;
        new (): HTMLWcLightModalElement;
    };
    interface HTMLElementTagNameMap {
        "wc-light-modal": HTMLWcLightModalElement;
    }
}
declare namespace LocalJSX {
    interface WcLightModal {
        "modalAnchor"?: string;
        "modalContent"?: string;
        "modalTitle"?: string;
        "x"?: number;
        "y"?: number;
    }
    interface IntrinsicElements {
        "wc-light-modal": WcLightModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-light-modal": LocalJSX.WcLightModal & JSXBase.HTMLAttributes<HTMLWcLightModalElement>;
        }
    }
}
