/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcGoAutocomplete {
        "category": string;
        "maxResults": number;
        "placeholder": string;
        "value": string;
    }
}
declare global {
    interface HTMLWcGoAutocompleteElement extends Components.WcGoAutocomplete, HTMLStencilElement {
    }
    var HTMLWcGoAutocompleteElement: {
        prototype: HTMLWcGoAutocompleteElement;
        new (): HTMLWcGoAutocompleteElement;
    };
    interface HTMLElementTagNameMap {
        "wc-go-autocomplete": HTMLWcGoAutocompleteElement;
    }
}
declare namespace LocalJSX {
    interface WcGoAutocomplete {
        "category"?: string;
        "maxResults"?: number;
        "onItemSelected"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "wc-go-autocomplete": WcGoAutocomplete;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-go-autocomplete": LocalJSX.WcGoAutocomplete & JSXBase.HTMLAttributes<HTMLWcGoAutocompleteElement>;
        }
    }
}
